DROP TABLE APP.COMMENT;
DROP TABLE USER_POST_SUBJECT_PUBLICATIONRELATION;
DROP TABLE APP.POST;
DROP TABLE APP.SUBJECT;
DROP TABLE APP.USER_;
DROP TABLE APP.DEGREE;
DROP TABLE APP.UNIVERSITY;
DROP TABLE APP.ADDRESS;
DROP TABLE APP.PROVINCE;
DROP TABLE APP.AUTONOMOUSCOMMUNITY;
DROP TABLE APP.USER_POST_FAVOURITERELATION;
DROP TABLE USER_POST_LIKEDRELATION;
DROP TABLE USER_SUBJECT_FOLLOWEDRELATION;
DROP TABLE APP.ROL;




