DROP TABLE APP.COMMENT;
DROP TABLE APP.USER_POST_R;
DROP TABLE USER_POST_SUBJECT_R;
DROP TABLE APP.POST;
DROP TABLE APP.SUBJECT;
DROP TABLE APP.USER_;
DROP TABLE APP.DEGREE;
DROP TABLE APP.ROL;
DROP TABLE APP.UNIVERSITY;
DROP TABLE APP.ADDRESS;
DROP TABLE USER_SUBJECT_R;

